### PR TITLE
Czech localization

### PR DESCRIPTION
**Pull request by karlitos**
Czech translations as promissed. I used the Poedit for mac ... so fingers crossed this would be ok.

### CODE REVIEW

**Comment by RaphaelRochet** [comment]
Man this one is such a mess ... I can't merge it like that.
I have cherry-picked your 77f168073f5a11d3c495a7b454bb473da1f30cdd commit to avoid rewriting everything :fearful:  ( became 6b06823 ).

**Comment by RaphaelRochet** [comment]
Seems you made deece8f368f07c92b6b02ebce56964fe19bfd8a5 , 8ece919  and  fc8ae55 after I forked your work ... I wonder If I should get them back.  Was there some issue with the CSS way of styling ? (Apart from not having preferences)
I made changes on tootlip style later too :  b79b825ab84faca9b71dae58b43d5d6f56761f27 some of theses changes seems to be taken from your work too .. can't remember :worried:

**Comment by RaphaelRochet** [comment]
Thanks for the translation too !

**Comment by karlitos** [comment]
Sorry for the mess, I will probably completely rebase on your repository state and put my master to same branch. I will look at my CSS if this may be an improvement.

**Pull request closed without merging**
